### ISSUE TITLE
No module named 'tkinter'

### ISSUE THREAD

**Issue by MuRKuo** [Zerotistic/auto-ropper#2]
└─(07:41:31 on main ✭)──> python3 main.py local             1 ↵ ──(Tue,May03)─┘
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from utils.gui import Gui
  File "/home/mosen/auto-ropper/utils/gui.py", line 1, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

**Comment by MuRKuo** [comment]
you can use `apt-get install tcl-dev tk-dev python3-tk -y`to handle it

**Comment by 0x00Jeff** [comment]
I had this issue as well, pls fix

**Comment by Zerotistic** [comment]
> you can use `apt-get install tcl-dev tk-dev python3-tk -y`to handle it

I'll see if i can use the lib from Python3, otherwise i'll add it to the installation part of the README.md.

Thanks!
